title: Massive Computational Experiments, Painlessly (STATS 285)
show_downloads: false
google_analytics:
theme:
gems:
  - jekyll-mentions
plugins:
  - jekyll-seo-tag 
markdown: redcarpet
highlighter: pygments


  
